trigger:
- main


jobs:
- job: linting
  displayName: 'Linting'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '18.x'
      checkLatest: true

  - script: |
      echo "##vso[task.setvariable variable=nodeVersion]$(node -v)"
    displayName: 'Get node version'

  - task: CacheBeta@0
    inputs:
      key: 'node|$(Agent.OS)|$(Build.SourcesDirectory)/**/package-lock.json|$(nodeVersion)'
      path: '**/node_modules'

  - script: |
      npm ci --no-audit --prefer-offline --progress=false
    displayName: 'Install dependencies'
    condition: ne(variables['Agent.CacheRestored'], 'true')

  - script: |
      npm run prettier:check
    displayName: 'Check prettier'

  - script: |
      npm run lint:check
    displayName: 'Check ESLinter'
