trigger:
- main

stages:
- stage: Lint
  displayName: 'Lint'
  jobs:
  - job: linting
    displayName: 'Linting'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: '18.x'
        checkLatest: true

    - script: |
        echo "##vso[task.setvariable variable=nodeVersion]$(node -v)"
      displayName: 'Get node version'

    - script: |
        npm ci --no-audit --prefer-offline --progress=false
      displayName: 'Install dependencies'

    - script: |
        npm run prettier:check
      displayName: 'Check prettier'

- stage: Build
  displayName: 'Build'
  jobs:
  - job: 
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: '16.x'
        checkLatest: true

    - script: |
        echo "##vso[task.setvariable variable=nodeVersion]$(node -v)"
      displayName: 'Get node version'

    - script: |
        npm ci --no-audit --prefer-offline --progress=false
      displayName: 'Install dependencies'

    - script: |
        npx nx build demo
      displayName: 'Build demo'

- stage: UnitTest
  displayName: 'Unit Test'
  jobs:

  - job: unit_testing
    displayName: 'Unit Testing'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: '18.x'
        checkLatest: true

    - script: |
        echo "##vso[task.setvariable variable=nodeVersion]$(node -v)"
      displayName: 'Get node version'

    - script: |
        npm ci --no-audit --prefer-offline --progress=false
      displayName: 'Install dependencies'

    - script: |
        npm run test --ci --lastCommit --maxWorkers=50%
      displayName: 'Check unit tests'
      continueOnError: true


- stage: DockerbuildPush
  displayName: 'Containerize'
  jobs:
  - job: buildandpush
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: realworldacr
        repository: realworldapp
        tags: '$(Build.BuildNumber)'